parameters:
  dependencies:
    additionalDirectories:
      - specification/oracle/models
    default: ""
  service-dir:
    default: sdk/oracledatabase
emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    arm-types-dir: ../../../../../common-types/resource-management
    azure-resource-provider-folder: resource-manager
    emitter-output-dir: "{project-root}/.."
    examples-directory: examples
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/openapi.json"
    use-read-only-status-schema: true
  "@azure-tools/typespec-go":
    examples-directory: ./examples
    generate-fakes: true
    head-as-boolean: true
    inject-spans: true
    module: github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/oracledatabase/armoracledatabase
    package-dir: resourcemanager/oracledatabase/armoracledatabase
    remove-unreferenced-types: true
    service-dir: sdk
  "@azure-tools/typespec-ts":
    flavor: azure
    package-dir: arm-oracledatabase
    packageDetails:
      name: "@azure/arm-oracledatabase"
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"