parameters:
  service-dir:
    default: sdk/vmware
  service-directory-name:
    default: vmware
emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    azure-resource-provider-folder: resource-manager
    emitter-output-dir: "{project-root}/.."
    examples-directory: "{project-root}/examples"
    omit-unreachable-types: true
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/vmware.json"
    use-read-only-status-schema: true
  "@azure-tools/typespec-go":
    examples-directory: ./examples
    generate-fakes: true
    head-as-boolean: true
    inject-spans: true
    module: github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/avs/armavs
    package-dir: resourcemanager/avs/armavs
    remove-unreferenced-types: true
    service-dir: sdk
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
