# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-rest-api-specs/main/documentation/api-scenario/references/v1.2/schema.json

scope: Subscription
variables:
  resourceProviderNamespace:
    type: string
  resourceType:
    type: string
  targetRegion:
    type: string
    value: West Central US
  targetApiVersion:
    type: string
scenarios:
  - scenario: checkServiceDeployment
    steps:
      - step: checkProviderAtTenantScope
        operationId: Providers_GetAtTenantScope
        responses:
          200:
            - test: /body/resourceTypes
              expression: >
                to.satisfy(function (val) {
                  return val.some((t) => t.resourceType === "$(resourceType)"
                    && t.locations.includes("$(targetRegion)")
                    && t.apiVersions.includes("$(targetApiVersion)"))
                },
                "ResourceType '$(resourceType)' should be deployed in '$(targetRegion)' on apiVersion '$(targetApiVersion)'.")
      - step: checkProviderAtSubscriptionScope
        operationId: Providers_Get
        responses:
          200:
            - test: /body/resourceTypes
              expression: >
                to.satisfy(function (val) {
                  return val.some((t) => t.resourceType === "$(resourceType)"
                    && t.locations.includes("$(targetRegion)")
                    && t.apiVersions.includes("$(targetApiVersion)"))
                },
                "ResourceType '$(resourceType)' should be deployed in '$(targetRegion)' on apiVersion '$(targetApiVersion)'.")
      - step: registerProviderForSubscription
        operationId: Providers_Register
