scope: ResourceGroup

scenarios:
  - scenario: Deployments
    description: Microsoft.Resources/deployments
    steps:
      - step: ResourceGroup_CalculateTemplateHash
        exampleFile: ../examples/CalculateTemplateHash.json

      - step: PostDeploymentWhatIfOnManagementGroup
        exampleFile: ../examples/PostDeploymentWhatIfOnManagementGroup.json

      - step: PostDeploymentWhatIfOnResourceGroup
        exampleFile: ../examples/PostDeploymentWhatIfOnResourceGroup.json

      - step: PostDeploymentWhatIfOnSubscription
        exampleFile: ../examples/PostDeploymentWhatIfOnSubscription.json
      
      - step: PostDeploymentWhatIfOnTenant
        exampleFile: ../examples/PostDeploymentWhatIfOnTenant.json

      - step: PutDeploymentAtManagementGroup
        exampleFile: ../examples/PutDeploymentAtManagementGroup.json

      - step: PutDeploymentAtScope
        exampleFile: ../examples/PutDeploymentAtScope.json

      - step: PutDeploymentAtTenant
        exampleFile: ../examples/PutDeploymentAtTenant.json

      - step: PutDeploymentResourceGroup
        exampleFile: ../examples/PutDeploymentResourceGroup.json

      - step: PutDeploymentResourceGroupTemplateSpecsWithId
        exampleFile: ../examples/PutDeploymentResourceGroupTemplateSpecsWithId.json

      - step: PutDeploymentSubscriptionTemplateSpecsWithId
        exampleFile: ../examples/PutDeploymentSubscriptionTemplateSpecsWithId.json
      
      - step: PutDeploymentWithOnErrorDeploymentLastSuccessful
        exampleFile: ../examples/PutDeploymentWithOnErrorDeploymentLastSuccessful.json

      - step: PutDeploymentWithOnErrorDeploymentSpecificDeployment
        exampleFile: ../examples/PutDeploymentWithOnErrorDeploymentSpecificDeployment.json
