# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-rest-api-specs/main/documentation/api-scenario/references/v1.2/schema.json
scope: ResourceGroup

variables:
  serverName:
    type: string
    prefix: serverna

prepareSteps:
  - step: Servers_Create
    exampleFile: ..\examples\ServerCreate.json

scenarios:
  - scenario: Configurations
    description: Microsoft.DBforPostgreSQL/flexibleServers/{serverName}/configurations/{configurationName}
    variables:
      configurationName:
        type: string
        prefix: configur
    steps:
      - operationId: Configurations_Put
        exampleFile: ..\examples\ConfigurationUpdate.json
      - operationId: Configurations_ListByServer
        exampleFile: ..\examples\ConfigurationListByServer.json
      - operationId: Configurations_Get
        exampleFile: ..\examples\ConfigurationGet.json
      - operationId: Configurations_Update
        exampleFile: ..\examples\ConfigurationUpdate.json
