scope: ResourceGroup
testScenarios:
  - description: test_network_cross_region_load_balancer_ip_config
    steps:
      - step: RawStep_1620
        method: GET
        rawUrl: >-
          https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/cli_test_cross_region_load_balancer_ip_config000001?api-version=2020-10-01
        requestHeaders:
          Accept: application/json
          Accept-Encoding: gzip, deflate
          CommandName: network public-ip create
          Connection: keep-alive
          ParameterSetName: '-g -n --sku'
          User-Agent: >-
            python/3.7.3 (Windows-10-10.0.19041-SP0) msrest/0.6.21
            msrest_azure/0.6.3 azure-mgmt-resource/12.0.0 Azure-SDK-For-Python
            AZURECLI/2.20.0
          accept-language: en-US
        responseExpected: >-
          {"id":"/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/cli_test_cross_region_load_balancer_ip_config000001","name":"cli_test_cross_region_load_balancer_ip_config000001","type":"Microsoft.Resources/resourceGroups","location":"westus","tags":{"product":"azurecli","cause":"automation","date":"2021-03-04T06:22:44Z"},"properties":{"provisioningState":"Succeeded"}}
      - step: Create_publicIPAddresses_publicip1
        resourceName: publicIPAddresses_publicip1
        exampleFile: ../examples/Create_publicIPAddresses_publicip1_Generated.json
        operationId: PublicIPAddresses_CreateOrUpdate
      - step: RawStep_1622
        method: GET
        rawUrl: >-
          https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/cli_test_cross_region_load_balancer_ip_config000001?api-version=2020-10-01
        requestHeaders:
          Accept: application/json
          Accept-Encoding: gzip, deflate
          CommandName: network public-ip create
          Connection: keep-alive
          ParameterSetName: '-g -n --sku'
          User-Agent: >-
            python/3.7.3 (Windows-10-10.0.19041-SP0) msrest/0.6.21
            msrest_azure/0.6.3 azure-mgmt-resource/12.0.0 Azure-SDK-For-Python
            AZURECLI/2.20.0
          accept-language: en-US
        responseExpected: >-
          {"id":"/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/cli_test_cross_region_load_balancer_ip_config000001","name":"cli_test_cross_region_load_balancer_ip_config000001","type":"Microsoft.Resources/resourceGroups","location":"westus","tags":{"product":"azurecli","cause":"automation","date":"2021-03-04T06:22:44Z"},"properties":{"provisioningState":"Succeeded"}}
      - step: Create_publicIPAddresses_publicip2
        resourceName: publicIPAddresses_publicip2
        exampleFile: ../examples/Create_publicIPAddresses_publicip2_Generated.json
        operationId: PublicIPAddresses_CreateOrUpdate
        variables:
          publicIpAddressName: publicip2
      - step: RawStep_1624
        method: GET
        rawUrl: >-
          https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/cli_test_cross_region_load_balancer_ip_config000001?api-version=2020-10-01
        requestHeaders:
          Accept: application/json
          Accept-Encoding: gzip, deflate
          CommandName: network public-ip create
          Connection: keep-alive
          ParameterSetName: '-g -n --sku'
          User-Agent: >-
            python/3.7.3 (Windows-10-10.0.19041-SP0) msrest/0.6.21
            msrest_azure/0.6.3 azure-mgmt-resource/12.0.0 Azure-SDK-For-Python
            AZURECLI/2.20.0
          accept-language: en-US
        responseExpected: >-
          {"id":"/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/cli_test_cross_region_load_balancer_ip_config000001","name":"cli_test_cross_region_load_balancer_ip_config000001","type":"Microsoft.Resources/resourceGroups","location":"westus","tags":{"product":"azurecli","cause":"automation","date":"2021-03-04T06:22:44Z"},"properties":{"provisioningState":"Succeeded"}}
      - step: Create_publicIPAddresses_publicip3
        resourceName: publicIPAddresses_publicip3
        exampleFile: ../examples/Create_publicIPAddresses_publicip3_Generated.json
        operationId: PublicIPAddresses_CreateOrUpdate
        variables:
          publicIpAddressName: publicip3
      - step: RawStep_1626
        method: GET
        rawUrl: >-
          https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/cli_test_cross_region_load_balancer_ip_config000001?api-version=2020-10-01
        requestHeaders:
          Accept: application/json
          Accept-Encoding: gzip, deflate
          CommandName: network cross-region-lb create
          Connection: keep-alive
          ParameterSetName: '-g -n --public-ip-address'
          User-Agent: >-
            python/3.7.3 (Windows-10-10.0.19041-SP0) msrest/0.6.21
            msrest_azure/0.6.3 azure-mgmt-resource/12.0.0 Azure-SDK-For-Python
            AZURECLI/2.20.0
          accept-language: en-US
        responseExpected: >-
          {"id":"/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/cli_test_cross_region_load_balancer_ip_config000001","name":"cli_test_cross_region_load_balancer_ip_config000001","type":"Microsoft.Resources/resourceGroups","location":"westus","tags":{"product":"azurecli","cause":"automation","date":"2021-03-04T06:22:44Z"},"properties":{"provisioningState":"Succeeded"}}
      - step: RawStep_1627
        method: GET
        rawUrl: >-
          https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resources?$filter=resourceGroup%20eq%20%27cli_test_cross_region_load_balancer_ip_config000001%27%20and%20name%20eq%20%27publicip1%27%20and%20resourceType%20eq%20%27Microsoft.Network%2FpublicIPAddresses%27&api-version=2020-10-01
        requestHeaders:
          Accept: application/json
          Accept-Encoding: gzip, deflate
          CommandName: network cross-region-lb create
          Connection: keep-alive
          ParameterSetName: '-g -n --public-ip-address'
          User-Agent: >-
            python/3.7.3 (Windows-10-10.0.19041-SP0) msrest/0.6.21
            msrest_azure/0.6.3 azure-mgmt-resource/12.0.0 Azure-SDK-For-Python
            AZURECLI/2.20.0
          accept-language: en-US
        responseExpected: >-
          {"value":[{"id":"/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/cli_test_cross_region_load_balancer_ip_config000001/providers/Microsoft.Network/publicIPAddresses/publicip1","name":"publicip1","type":"Microsoft.Network/publicIPAddresses","sku":{"name":"Standard"},"location":"westus"}]}
      - step: RawStep_1628
        method: PUT
        rawUrl: >-
          https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/cli_test_cross_region_load_balancer_ip_config000001/providers/Microsoft.Resources/deployments/mock-deployment?api-version=2020-10-01
        requestBody: >-
          {"properties":{"template":{"$schema":"https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#","contentVersion":"1.0.0.0","parameters":{},"variables":{},"resources":[{"type":"Microsoft.Network/loadBalancers","name":"lb1","location":"westus","tags":{},"apiVersion":"2020-11-01","dependsOn":[],"properties":{"backendAddressPools":[{"name":"lb1bepool"}],"frontendIPConfigurations":[{"name":"LoadBalancerFrontEnd","properties":{"publicIPAddress":{"id":"/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/cli_test_cross_region_load_balancer_ip_config000001/providers/Microsoft.Network/publicIPAddresses/publicip1"}}}]},"sku":{"name":"standard","tier":"Global"}}],"outputs":{"loadBalancer":{"type":"object","value":"[reference('lb1')]"}}},"parameters":{},"mode":"Incremental"}}
        requestHeaders:
          Accept: application/json
          Accept-Encoding: gzip, deflate
          CommandName: network cross-region-lb create
          Connection: keep-alive
          Content-Length: '883'
          Content-Type: application/json; charset=utf-8
          ParameterSetName: '-g -n --public-ip-address'
          User-Agent: >-
            python/3.7.3 (Windows-10-10.0.19041-SP0) msrest/0.6.21
            msrest_azure/0.6.3 azure-mgmt-resource/12.0.0 Azure-SDK-For-Python
            AZURECLI/2.20.0
          accept-language: en-US
        statusCode: 201
        responseExpected: >-
          {"id":"/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/cli_test_cross_region_load_balancer_ip_config000001/providers/Microsoft.Resources/deployments/lb_deploy_S7G1uDmBcF6JvFoMpvFxfyd6ODH63EFw","name":"lb_deploy_S7G1uDmBcF6JvFoMpvFxfyd6ODH63EFw","type":"Microsoft.Resources/deployments","properties":{"templateHash":"3388102344198172420","parameters":{},"mode":"Incremental","provisioningState":"Accepted","timestamp":"2021-03-04T06:23:13.4716039Z","duration":"PT1.9511082S","correlationId":"2d5e4654-b590-46f8-8a5f-fe0f2b863a16","providers":[{"namespace":"Microsoft.Network","resourceTypes":[{"resourceType":"loadBalancers","locations":["westus"]}]}],"dependencies":[]}}
      - step: RawStep_1629
        method: GET
        rawUrl: >-
          https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/cli_test_cross_region_load_balancer_ip_config000001/providers/Microsoft.Resources/deployments/mock-deployment/operationStatuses/08585867678939571208?api-version=2020-10-01
        requestHeaders:
          Accept: application/json
          Accept-Encoding: gzip, deflate
          CommandName: network cross-region-lb create
          Connection: keep-alive
          ParameterSetName: '-g -n --public-ip-address'
          User-Agent: >-
            python/3.7.3 (Windows-10-10.0.19041-SP0) msrest/0.6.21
            msrest_azure/0.6.3 azure-mgmt-resource/12.0.0 Azure-SDK-For-Python
            AZURECLI/2.20.0
        responseExpected: '{"status":"Succeeded"}'
      - step: RawStep_1630
        method: GET
        rawUrl: >-
          https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/cli_test_cross_region_load_balancer_ip_config000001/providers/Microsoft.Resources/deployments/mock-deployment?api-version=2020-10-01
        requestHeaders:
          Accept: application/json
          Accept-Encoding: gzip, deflate
          CommandName: network cross-region-lb create
          Connection: keep-alive
          ParameterSetName: '-g -n --public-ip-address'
          User-Agent: >-
            python/3.7.3 (Windows-10-10.0.19041-SP0) msrest/0.6.21
            msrest_azure/0.6.3 azure-mgmt-resource/12.0.0 Azure-SDK-For-Python
            AZURECLI/2.20.0
        responseExpected: >-
          {"id":"/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/cli_test_cross_region_load_balancer_ip_config000001/providers/Microsoft.Resources/deployments/lb_deploy_S7G1uDmBcF6JvFoMpvFxfyd6ODH63EFw","name":"lb_deploy_S7G1uDmBcF6JvFoMpvFxfyd6ODH63EFw","type":"Microsoft.Resources/deployments","properties":{"templateHash":"3388102344198172420","parameters":{},"mode":"Incremental","provisioningState":"Succeeded","timestamp":"2021-03-04T06:23:28.1280371Z","duration":"PT16.6075414S","correlationId":"2d5e4654-b590-46f8-8a5f-fe0f2b863a16","providers":[{"namespace":"Microsoft.Network","resourceTypes":[{"resourceType":"loadBalancers","locations":["westus"]}]}],"dependencies":[],"outputs":{"loadBalancer":{"type":"Object","value":{"provisioningState":"Succeeded","resourceGuid":"71ecb9f2-2901-43b2-b140-abeb0eb67f18","frontendIPConfigurations":[{"name":"LoadBalancerFrontEnd","id":"/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/cli_test_cross_region_load_balancer_ip_config000001/providers/Microsoft.Network/loadBalancers/lb1/frontendIPConfigurations/LoadBalancerFrontEnd","etag":"W/\"79dda067-c096-446a-818a-abc78c00ea8d\"","type":"Microsoft.Network/loadBalancers/frontendIPConfigurations","properties":{"provisioningState":"Succeeded","privateIPAllocationMethod":"Dynamic","publicIPAddress":{"id":"/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/cli_test_cross_region_load_balancer_ip_config000001/providers/Microsoft.Network/publicIPAddresses/publicip1"},"privateIPAddressVersion":"IPv4"}}],"backendAddressPools":[{"name":"lb1bepool","id":"/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/cli_test_cross_region_load_balancer_ip_config000001/providers/Microsoft.Network/loadBalancers/lb1/backendAddressPools/lb1bepool","etag":"W/\"79dda067-c096-446a-818a-abc78c00ea8d\"","properties":{"provisioningState":"Succeeded","loadBalancerBackendAddresses":[]},"type":"Microsoft.Network/loadBalancers/backendAddressPools"}],"loadBalancingRules":[],"probes":[],"inboundNatRules":[],"outboundRules":[],"inboundNatPools":[]}}},"outputResources":[{"id":"/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/cli_test_cross_region_load_balancer_ip_config000001/providers/Microsoft.Network/loadBalancers/lb1"}]}}
      - step: LoadBalancers_Get_1631
        exampleFile: ../examples/LoadBalancers_Get_1631_Generated.json
        operationId: LoadBalancers_Get
      - step: Create_loadBalancers_lb1
        resourceName: loadBalancers_lb1
        exampleFile: ../examples/Create_loadBalancers_lb1_Generated_1633.json
        operationId: LoadBalancers_CreateOrUpdate
      - step: Update_loadBalancers_lb1_1635
        resourceName: loadBalancers_lb1
        operationId: LoadBalancers_CreateOrUpdate
        resourceUpdate:
          - replace: >-
              /properties/frontendIPConfigurations/1/properties/publicIPAddress/id
            value: >-
              /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/cli_test_cross_region_load_balancer_ip_config000001/providers/Microsoft.Network/publicIPAddresses/publicip3
      - step: Update_loadBalancers_lb1_1637
        resourceName: loadBalancers_lb1
        operationId: LoadBalancers_CreateOrUpdate
        resourceUpdate:
          - replace: >-
              /properties/frontendIPConfigurations/1/properties/publicIPAddress/id
            value: >-
              /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/cli_test_cross_region_load_balancer_ip_config000001/providers/Microsoft.Network/publicIPAddresses/publicip2
      - step: Update_loadBalancers_lb1_1639
        resourceName: loadBalancers_lb1
        operationId: LoadBalancers_CreateOrUpdate
        resourceUpdate:
          - remove: /properties/frontendIPConfigurations/1
    variables:
      publicIpAddressName: publicip1
      loadBalancerName: lb1
