emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    azure-resource-provider-folder: resource-manager
    emitter-output-dir: "{project-root}/.."
    examples-directory: examples
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/verifiedid.json"
    use-read-only-status-schema: true
  "@azure-tools/typespec-go":
    examples-directory: ./examples
    generate-fakes: true
    head-as-boolean: true
    inject-spans: true
    module: github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/verifiedid/armverifiedid
    package-dir: resourcemanager/verifiedid/armverifiedid
    remove-unreferenced-types: true
    service-dir: sdk
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
