parameters:
  service-dir:
    default: sdk/devopsinfrastructure
emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/cadl-csharp":
    clear-output-folder: true
    model-namespace: false
    namespace: Microsoft.DevOpsInfrastructure
    save-inputs: false
  "@azure-tools/typespec-autorest":
    azure-resource-provider-folder: resource-manager
    emitter-output-dir: "{project-root}/.."
    examples-directory: "{project-root}/examples"
    omit-unreachable-types: true
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/devopsinfrastructure.json"
  "@azure-tools/typespec-go":
    examples-directory: ./examples
    generate-fakes: true
    head-as-boolean: true
    inject-spans: true
    module: github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/devopsinfrastructure/armdevopsinfrastructure
    package-dir: resourcemanager/devopsinfrastructure/armdevopsinfrastructure
    remove-unreferenced-types: true
    service-dir: sdk
  "@azure-tools/typespec-java":
    examples-directory: examples
    flavor: azure
    namespace: com.azure.resourcemanager.devopsinfrastructure
    package-dir: azure-resourcemanager-devopsinfrastructure
    service-name: DevOps Infrastructure
  "@azure-tools/typespec-python":
    flavor: azure
    package-dir: azure-mgmt-devopsinfrastructure
    package-name: "{package-dir}"
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
  disable:
    "@azure-tools/typespec-azure-resource-manager/arm-common-types-version": New rule
