parameters:
  service-dir:
    default: sdk/standbypool
emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    azure-resource-provider-folder: resource-manager
    emitter-output-dir: "{project-root}/.."
    examples-directory: "{project-root}/examples"
    omit-unreachable-types: true
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/standbypool.json"
    use-read-only-status-schema: true
  "@azure-tools/typespec-go":
    examples-directory: ./examples
    generate-fakes: true
    head-as-boolean: true
    inject-spans: true
    module: github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/standbypool/armstandbypool
    package-dir: resourcemanager/standbypool/armstandbypool
    remove-unreferenced-types: true
    service-dir: sdk
  "@azure-tools/typespec-java":
    examples-directory: examples
    flavor: azure
    namespace: com.azure.resourcemanager.standbypool
    package-dir: azure-resourcemanager-standbypool
    service-name: Standby Pool
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
