# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-rest-api-specs/main/documentation/api-scenario/references/v1.2/schema.json
scope: ResourceGroup

scenarios:
  - scenario: ManagedEnvironmentsStorages
    description: Microsoft.App/managedEnvironments/{environmentName}/storages/{storageName}
    steps:
      - operationId: ManagedEnvironmentsStorages_CreateOrUpdate
        exampleFile: ..\examples\ManagedEnvironmentsStorages_CreateOrUpdate.json
      - operationId: ManagedEnvironmentsStorages_List
        exampleFile: ..\examples\ManagedEnvironmentsStorages_List.json
      - operationId: ManagedEnvironmentsStorages_Get
        exampleFile: ..\examples\ManagedEnvironmentsStorages_Get.json
      - operationId: ManagedEnvironmentsStorages_Delete
        exampleFile: ..\examples\ManagedEnvironmentsStorages_Delete.json
