# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-rest-api-specs/main/documentation/api-scenario/references/v1.2/schema.json
scope: ResourceGroup

scenarios:
  - scenario:  ApplicationSecurityGroup
    description: Microsoft.Network/applicationSecurityGroups
    steps:
      - step: ApplicationSecurityGroup_Create
        exampleFile: ../examples/ApplicationSecurityGroupCreate.json
      - step: ApplicationSecurityGroup_UpdateTag
        exampleFile: ../examples/ApplicationSecurityGroupCreate.json
      - step: ApplicationSecurityGroup_Get
        exampleFile: ../examples/ApplicationSecurityGroupGet.json
      - step: ApplicationSecurityGroup_List
        exampleFile: ../examples/ApplicationSecurityGroupList.json
      - step: ApplicationSecurityGroup_ListAll
        exampleFile: ../examples/ApplicationSecurityGroupListAll.json
      - step: ApplicationSecurityGroup_Delete
        exampleFile: ../examples/ApplicationSecurityGroupDelete.json
