# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-rest-api-specs/main/documentation/api-scenario/references/v1.2/schema.json
scope: ResourceGroup

scenarios:
  - scenario: ApplicationGateway
    description: Microsoft.Network/applicationGateways CRUD
    steps:
      - step: ApplicationGateway_Create
        exampleFile: ../examples/ApplicationGatewayCreate.json
        # requestUpdate:
        #   - replace: /parameters/identity
        #     value:
        #       type: UserAssigned
        #       userAssignedIdentities:
        #         /subscription/$(subscriptionId)/resourceGroups/$(resourceGroupName)/providers/Microsoft.ManagedIdentity/userAssignedIdentities/identity1: {}
      - step: ApplicationGateway_UpdateTags
        exampleFile: ../examples/ApplicationGatewayUpdateTags.json
      - step: ApplicationGateway_Get
        exampleFile: ../examples/ApplicationGatewayGet.json
      - step: ApplicationGateway_List
        exampleFile: ../examples/ApplicationGatewayList.json
      - step: ApplicationGateway_ListAll
        exampleFile: ../examples/ApplicationGatewayListAll.json
      - step: ApplicationGateway_BackendHealth
        exampleFile: ../examples/ApplicationGatewayBackendHealthGet.json
      - step: ApplicationGateway_Stop
        exampleFile: ../examples/ApplicationGatewayStop.json
      - step: ApplicationGateway_Start
        exampleFile: ../examples/ApplicationGatewayStart.json
      - step: ApplicationGateway_Delete
        exampleFile: ../examples/ApplicationGatewayDelete.json

