emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    azure-resource-provider-folder: resource-manager
    emitter-output-dir: "{project-root}/.."
    examples-directory: "{project-root}/examples"
    omit-unreachable-types: true
    emit-common-types-schema: "never"
    # `arm-resource-flattening` is only used for back-compat for specs existed on July 2024. All new service spec should NOT use this flag
    arm-resource-flattening: true
    output-file: "{azure-resource-provider-folder}/{service-name}/monitors/{version-status}/{version}/monitors.json"
    use-read-only-status-schema: true
  "@azure-tools/typespec-go":
    examples-directory: ./examples
    generate-fakes: true
    head-as-boolean: true
    inject-spans: true
    module: github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/workloads/armworkloads
    package-dir: resourcemanager/workloads/armworkloads
    remove-unreferenced-types: true
    service-dir: sdk
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
