parameters:
  dependencies:
    additionalDirectories: []
    default: ""
  service-dir:
    default: sdk/appcomplianceautomation
emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    azure-resource-provider-folder: resource-manager
    emitter-output-dir: "{project-root}/.."
    emit-common-types-schema: "never"
    # `arm-resource-flattening` is only used for back-compat for specs existed on July 2024. All new service spec should NOT use this flag
    arm-resource-flattening: true
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/appcomplianceautomation.json"
    examples-directory: "{project-root}/examples"
    use-read-only-status-schema: true
  "@azure-tools/typespec-go":
    examples-directory: ./examples
    generate-fakes: true
    head-as-boolean: true
    inject-spans: true
    module: github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/appcomplianceautomation/armappcomplianceautomation
    package-dir: resourcemanager/appcomplianceautomation/armappcomplianceautomation
    remove-unreferenced-types: true
    service-dir: sdk
  "@azure-tools/typespec-ts":
    examples-directory: "{project-root}/examples"
    flavor: azure
    package-dir: arm-appcomplianceautomation
    packageDetails:
      name: "@azure/arm-appcomplianceautomation"
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
