# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-rest-api-specs/main/documentation/api-scenario/references/v1.2/schema.json
scope: ResourceGroup

scenarios:
  - scenario: Applications
    description: Microsoft.HDInsight/clusters/{clusterName}/applications/{applicationName}
    steps:
      - operationId: Applications_Create
        exampleFile: ..\examples\CreateApplication.json
      - operationId: Applications_ListByCluster
        exampleFile: ..\examples\GetAllApplications.json
      - operationId: Applications_Get
        exampleFile: ..\examples\GetApplicationCreated.json
      - operationId: Applications_GetAzureAsyncOperationStatus
        exampleFile: ..\examples\GetApplicationCreationAsyncOperationStatus.json
      - operationId: Applications_Delete
        exampleFile: ..\examples\DeleteApplication.json
