# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-rest-api-specs/main/documentation/api-scenario/references/v1.2/schema.json
scope: ResourceGroup

scenarios:
  - scenario: Configurations
    description: Microsoft.HDInsight/clusters/{clusterName}/configurations/{configurationName}
    steps:
      - operationId: Configurations_List
        exampleFile: ..\examples\HDI_Configurations_List.json
      - operationId: Configurations_Get
        exampleFile: ..\examples\HDI_Configurations_Get.json
      - operationId: Configurations_Update
        exampleFile: ..\examples\ChangeHttpConnectivityEnable.json
